
Test cache:
  image: node:14.15
  stage: test
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  script:
    - echo "hello"
    - yarn
    - echo "finished"


Test no cache:
  image: node:14.15
  stage: test
  script:
    - echo "hello"
    - yarn
    - echo "finished"
    

Test package manager cache:
  image: node:14.15
  stage: test
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - .cache
  script:
    - echo "hello"
    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - yarn
    - echo "finished"

