# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-nocache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Start without cache

      - name: yarn install
        run: |
          yarn
          echo "finished"
          
  build-cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: yarn install
        run: |
          yarn
          echo "finished"

  build-package-manager-cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          #
          echo "Node $(node --version)"
          echo "Yarn $(yarn --version)"
          #
          echo "::set-output name=yarn_cache::$(yarn cache dir)"
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Yarn packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup.outputs.yarn_cache }}
          key: ${{ runner.os }}-yarn_cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn_cache-

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: yarn install
        run: |
          yarn
          echo "finished"

      # Runs a set of commands using the runners shell
      - name: info
        run: |
          du -sh ${{ steps.setup.outputs.yarn_cache }}
          du -sh node_modules
